CREATE DATABASE ASSIGNMENTS
CREATE TABLE EMP_DETAIL (
EMP_ID INT PRIMARY KEY,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
SALARY MONEY,
JOINING_DATE VARCHAR(50),
DEPARTMENT VARCHAR(10),
GENDER VARCHAR(20))

SELECT * FROM EMP_DETAIL

INSERT INTO EMP_DETAIL VALUES
(1,'VIKASH','ALHAWAT','600000','02-12-2013','IT','MALE'),
(2,'NIKITA','JAIN','530000','02-14-2013','HR','FEMALE'),
(3,'ASHISH','KUMAR','1000000','02-14-2013','IT','MALE'),
(4,'NIKHIL','SHARMA','480000','02-15-2013','HR','MALE'),
(5,'ANISH','KADIAN','500000','02-16-2013','PAYROLL','MALE')

SELECT * FROM EMP_DETAIL---1

SELECT FIRSTNAME FROM EMP_DETAIL---2

SELECT LOWER(FIRSTNAME) AS FIRST_NAME FROM EMP_DETAIL---3---4

SELECT CONCAT(FIRSTNAME,' ',LASTNAME) AS NAME FROM EMP_DETAIL---5

SELECT * FROM EMP_DETAIL WHERE FIRSTNAME = 'VIKASH'----6

SELECT * FROM EMP_DETAIL WHERE FIRSTNAME LIKE 'A%'---7---8

SELECT * FROM EMP_DETAIL WHERE FIRSTNAME LIKE '%H'---9

SELECT * FROM EMP_DETAIL  WHERE LEFT(FIRSTNAME,1) BETWEEN 'A' AND 'P'---10
SELECT * FROM EMP_DETAIL  WHERE  FIRSTNAME LIKE '[A-P]%'----10

SELECT * FROM EMP_DETAIL  WHERE NOT (FIRSTNAME LIKE '[A-P]%')---11

SELECT * FROM EMP_DETAIL  WHERE GENDER LIKE '__LE%'---12

SELECT * FROM EMP_DETAIL  WHERE FIRSTNAME LIKE 'A____'---13

SELECT * FROM EMP_DETAIL  WHERE FIRSTNAME  LIKE '%\%%'-----14

SELECT DEPARTMENT,COUNT(*) HEADCOUNT FROM EMP_DETAIL GROUP BY DEPARTMENT----15
SELECT DISTINCT DEPARTMENT FROM EMP_DETAIL

SELECT * FROM EMP_DETAIL WHERE SALARY = (SELECT MAX(SALARY) FROM EMP_DETAIL)-----16
SELECT * FROM EMP_DETAIL ORDER BY SALARY DESC LIMIT 1;
SELECT * FROM EMP_DETAIL ORDER BY SALARY DESC LIMIT 1 OFFSET 1;----SECOND HIGHEST OFFSET 2 FOR THIRD

SELECT * FROM EMP_DETAIL WHERE SALARY = 
(SELECT MAX(SALARY) FROM EMP_DETAIL WHERE SALARY < ----SECOND HIGHEST
(SELECT MAX(SALARY) FROM EMP_DETAIL))

SELECT * FROM EMP_DETAIL WHERE SALARY = (SELECT MIN(SALARY) FROM EMP_DETAIL)------17

SELECT FIRSTNAME, FORMAT(JOINING_DATE ,'DD MMM YYYY') AS UPDATED_DATE FROM EMP_DETAIL -----18
SELECT FIRSTNAME,LASTNAME,YEAR(JOINING_DATE) AS JOINEDYEAR FROM EMP_DETAIL-----19
SELECT FIRSTNAME,LASTNAME,MONTH(JOINING_DATE) AS JOINEDYEAR FROM EMP_DETAIL-----20

SELECT GETDATE() AS CURRDATE -----23
SELECT GETUTCDATE() AS CURRUTCDATE-----24

SELECT FIRSTNAME,
GETDATE() AS CURRDATE,
JOINING_DATE,
DATEDIFF(MONTH,JOINING_DATE,GETDATE()) AS MONTH_DIFF ------24
FROM EMP_DETAIL

SELECT FIRSTNAME,
GETDATE() AS CURRDATE,
JOINING_DATE,
DATEDIFF(DAY,JOINING_DATE,GETDATE()) AS DAY_DIFF ------25
FROM EMP_DETAIL

SELECT * FROM EMP_DETAIL WHERE YEAR(JOINING_DATE) = 2013----26
SELECT * FROM EMP_DETAIL WHERE MONTH(JOINING_DATE) = 01----27---28

SELECT COUNT(*) FROM EMP_DETAIL-----29

SELECT TOP 1 * FROM EMP_DETAIL ORDER BY EMP_ID-----31

SELECT RTRIM(FIRSTNAME) FROM EMP_DETAIL
SELECT LTRIM(FIRSTNAME) FROM EMP_DETAIL

SELECT * FROM EMP_DETAIL WHERE FIRSTNAME IN ('VIKASH')
SELECT * FROM EMP_DETAIL WHERE FIRSTNAME NOT IN ('VIKASH')

SELECT FIRSTNAME,LEFT(GENDER,1) AS GEN FROM EMP_DETAIL----36

SELECT CONCAT('HELLO ',FIRSTNAME) FROM EMP_DETAIL ---37

SELECT * FROM EMP_DETAIL WHERE SALARY >700000----38
SELECT * FROM EMP_DETAIL WHERE SALARY <700000 ----39
SELECT * FROM EMP_DETAIL WHERE SALARY BETWEEN 700000 AND 1000000 ------40

----------------------------------------------------------------------------------------
CREATE TABLE PROJECT_DETAIL (
PROID INT PRIMARY KEY,
EMPID INT,
PROJECT_NAME VARCHAR(50))

SELECT * FROM PROJECT_DETAIL

INSERT INTO PROJECT_DETAIL VALUES 
(1,1,'TASK TRACK'),
(2,1,'CLP'),
(3,1,'SURVAY MANAGEMENT'),
(4,2,'HR MANAGEMENT'),
(5,3,'GRS'),
(6,3,'DDS'),
(7,3,'TASK TRACK'),
(8,4,'HR MANAGEMENT'),
(9,5,'GL MANAGEMENT')

SELECT * FROM PROJECT_DETAIL------41
SELECT * FROM EMP_DETAIL

SELECT DEPARTMENT,SUM(SALARY) FROM EMP_DETAIL GROUP BY DEPARTMENT ----42
SELECT DEPARTMENT,SUM(SALARY) FROM EMP_DETAIL GROUP BY DEPARTMENT ORDER BY SALARY ASC----43
SELECT DEPARTMENT,SUM(SALARY) FROM EMP_DETAIL GROUP BY DEPARTMENT ORDER BY SALARY ASC----44
SELECT DEPARTMENT,COUNT(DEPARTMENT),SUM(SALARY) FROM EMP_DETAIL GROUP BY DEPARTMENT ----45
SELECT DEPARTMENT,AVG(SALARY) FROM EMP_DETAIL GROUP BY DEPARTMENT ORDER BY SALARY ASC----46
SELECT DEPARTMENT,MAX(SALARY) FROM EMP_DETAIL GROUP BY DEPARTMENT ORDER BY SALARY ASC----47
SELECT DEPARTMENT,MIN(SALARY) FROM EMP_DETAIL GROUP BY DEPARTMENT ORDER BY SALARY ASC----49

SELECT * FROM PROJECT_DETAIL JOIN EMP_DETAIL ON EMP_ID = EMPID
SELECT * FROM PROJECT_DETAIL, EMP_DETAIL WHERE EMP_ID = EMPID-----50

SELECT FIRSTNAME,PROJECT_NAME FROM PROJECT_DETAIL INNER JOIN EMP_DETAIL ON EMP_ID =EMPID ORDER BY FIRSTNAME -----51

SELECT FIRSTNAME,PROJECT_NAME FROM PROJECT_DETAIL RIGHT JOIN EMP_DETAIL ON EMP_ID =EMPID WHERE EMPID IS NULL ORDER BY FIRSTNAME -----52

SELECT FIRSTNAME,COALESCE(PROJECT_NAME,'NO ASSIGNED PROJECT') AS PROJECT_NAME
FROM PROJECT_DETAIL RIGHT JOIN EMP_DETAIL ON EMP_ID =EMPID 
WHERE EMPID IS NULL ORDER BY FIRSTNAME ----------------------------------------------------53

SELECT FIRSTNAME,COALESCE(PROJECT_NAME,'NO ASSIGNED PROJECT') AS PROJECT_NAME----54
FROM PROJECT_DETAIL LEFT JOIN EMP_DETAIL ON EMP_ID =EMPID 
WHERE EMPID IS NULL ORDER BY FIRSTNAME 

SELECT FIRSTNAME,PROJECT_NAME
FROM PROJECT_DETAIL FULL JOIN
EMP_DETAIL ON EMP_ID =EMPID ----------55,56,57


SELECT FIRSTNAME,PROJECT_NAME,PROID,EMP_ID
FROM EMP_DETAIL JOIN PROJECT_DETAIL 
ON EMP_ID = EMPID 
GROUP BY FIRSTNAME,PROJECT_NAME,PROID,EMP_ID ------------58
HAVING COUNT(PROID) > 1
ORDER BY FIRSTNAME

SELECT P.PROJECT_NAME,E.FIRSTNAME FROM EMP_DETAIL E JOIN PROJECT_DETAIL P ON P.EMPID = E.EMP_ID
GROUP BY P.PROID,P.PROJECT_NAME,E.EMP_ID,E.FIRSTNAME HAVING COUNT(E.EMP_ID) >1 ------59

SELECT * FROM EMP_DETAIL CROSS JOIN PROJECT_DETAIL -------------60





























































































































































